/etc/bind/db.lks.id
$TTL    604800
@       IN      SOA     ns.lks.id. admin.lks.id. (
                              2         ; Serial
                         604800         ; Refresh
                          86400         ; Retry
                        2419200         ; Expire
                         604800 )       ; Negative Cache TTL
;
@               IN      NS      ns.lks.id.

gateway         IN      A       192.168.30.1
fw              IN      A       192.168.30.1
fw-srv          IN      A       192.168.30.1

ns              IN      A       192.168.30.2
internal        IN      A       192.168.30.2
internal-srv    IN      A       192.168.30.2

mail            IN      A       192.168.40.2
mail-srv        IN      A       192.168.40.2

web01           IN      A       192.168.40.3
web02           IN      A       192.168.40.3

www             IN      CNAME   web01.lks.id.
webmail         IN      CNAME   mail.lks.id.